### ISSUE TITLE
Harden your GitHub account

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-schenkh#1]
Enable 2FA:
* [ ] proceed at https://github.com/settings/security
* [ ] I recommend using the following OTP code generator: https://play.google.com/store/apps/details?id=org.liberty.android.freeotpplus&hl=en_US

**Comment by schenkh** [comment]
Enabled 2FA

**Comment by webknjaz** [comment]
According to my records, you have it configured. Closing.
