### ISSUE TITLE
Create an SSH key and add it to GitHub account

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-schenkh#3]
See:
* https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/#generating-a-new-ssh-key (you may omit adding a password)
* https://help.github.com/articles/connecting-to-github-with-ssh/

After completing instructions, post the result of the following command in a comment to this issue:
```shell
ssh -T git@github.com
```

**Comment by schenkh** [comment]
Warning: Permanently added the RSA host key for IP address 'bla-bla' to the list of known hosts.
Hi schenkh! You've successfully authenticated, but GitHub does not provide shell access.

**Comment by webknjaz** [comment]
@schenkh why did you remove the comment?

**Comment by schenkh** [comment]
Yes, since I was not sure if I need to comment or change issue status.

"Hi schenkh! You've successfully authenticated, but GitHub does not provide shell access."

**Comment by schenkh** [comment]
So I’ve actually completed the assignments you sent.

**Comment by webknjaz** [comment]
Completed assignments should be closed. And this one literally instructs you to post the result here.

**Comment by schenkh** [comment]
Ok, it was not assigned to me so I thought it might be some sort of "group
assignment". I will close the rest of them now, thanks for sorting it out.

**Comment by webknjaz** [comment]
This whole repository is for your assignments only.
